name: MasterDeployCI
on:
  push:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-verion: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version:${{matrix.node-version}}
    - name: Install Packages
      run:  npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email ${{secrets.EMAIL}}
        git config --global user.name ${{sercrets.USERNAME}} 
        git remote set-url origin https://${{secrets.ACCESS_TOKEN}}@github.com/${{sercrets.USERNAME}}/covid-tracker.git